some modules changed to use the new _init.sh initialize.

diff --git a/scripts/docker/svc-install b/scripts/docker/svc-install
--- a/scripts/docker/svc-install
+++ b/scripts/docker/svc-install
@@ -1,31 +1,25 @@
 #!/usr/bin/env bash
 
+source  ./scripts/_init.sh
+
 ########################################
 #   Note: suport CentOS 7 only
 ########################################
 
-set -e
-
-if [ "${1}" = "" ] ;then
-    host=${EASY_OP_SSH_HOST}
-else
-    host=${1}
-fi
-
 CONF_DIR=/etc/openresty
 
-ssh     ${host}    <<'EOF'
-set     -e
-command -v      docker  >/dev/null 2>&1 ||  {
-    curl    -fsSL   https://get.docker.com/ | sh || echo '' #don't check failure
-}
-command -v      docker  >/dev/null 2>&1 ||  {
-    exit    1
-}
-exit    0
+./scripts/run       ${EO_HOST}    <<'EOF'
+    set     -e
+    command -v      docker  >/dev/null 2>&1 ||  {
+        curl    -fsSL   https://get.docker.com/ | sh || echo '' #don't check failure
+    }
+    command -v      docker  >/dev/null 2>&1 ||  {
+        exit    1
+    }
+    exit    0
 EOF
 
-./scripts/reload     ${host}    docker
-./scripts/stop       ${host}    docker
+./scripts/reload     ${EO_HOST}    docker
+./scripts/stop       ${EO_HOST}    docker
 
-./scripts/docker/conf-update     ${host}
+./scripts/docker/conf-update     ${EO_HOST}
